OPENAI_API_KEY = "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"
APP_USERNAME = "intelligo"
APP_PASSWORD = "r1cyt"